export interface Game {
  id: string;
  name: string;
  category: string;
  description: string;
  icon: string;
  color: string;
  difficulty: 'easy' | 'medium' | 'hard';
  minPlayers: number;
  maxPlayers: number;
  estimatedTime: string;
  featured: boolean;
}

export const GAMES: Game[] = [
  // Puzzle Games
  {
    id: 'sudoku',
    name: 'Sudoku Master',
    category: 'Puzzle',
    description: 'Classic number puzzle with hints and auto-check',
    icon: '🔢',
    color: '#6366f1',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '10-20 min',
    featured: true,
  },
  {
    id: '2048',
    name: '2048 Deluxe',
    category: 'Puzzle',
    description: 'Combine tiles to reach 2048 and beyond',
    icon: '🎯',
    color: '#8b5cf6',
    difficulty: 'easy',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '5-15 min',
    featured: true,
  },
  {
    id: 'match3',
    name: 'Candy Crush',
    category: 'Puzzle',
    description: 'Match 3 or more candies for explosive combos',
    icon: '🍬',
    color: '#ec4899',
    difficulty: 'easy',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '5-10 min',
    featured: false,
  },
  {
    id: 'crossword',
    name: 'Crossword Challenge',
    category: 'Puzzle',
    description: 'Daily crossword puzzles with hints',
    icon: '📝',
    color: '#10b981',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '15-30 min',
    featured: false,
  },

  // Strategy Games
  {
    id: 'tictactoe',
    name: 'Tic Tac Toe Pro',
    category: 'Strategy',
    description: 'Classic game with AI and multiplayer',
    icon: '❌',
    color: '#3b82f6',
    difficulty: 'easy',
    minPlayers: 1,
    maxPlayers: 2,
    estimatedTime: '2-5 min',
    featured: true,
  },
  {
    id: 'chess',
    name: 'Chess Master',
    category: 'Strategy',
    description: 'Full chess with different AI levels',
    icon: '♟️',
    color: '#1f2937',
    difficulty: 'hard',
    minPlayers: 1,
    maxPlayers: 2,
    estimatedTime: '20-60 min',
    featured: true,
  },
  {
    id: 'checkers',
    name: 'Checkers Champion',
    category: 'Strategy',
    description: 'Classic checkers with strategy tips',
    icon: '🔴',
    color: '#ef4444',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 2,
    estimatedTime: '10-20 min',
    featured: false,
  },
  {
    id: 'connect4',
    name: 'Connect Four',
    category: 'Strategy',
    description: 'Connect 4 discs to win',
    icon: '🔵',
    color: '#0ea5e9',
    difficulty: 'easy',
    minPlayers: 1,
    maxPlayers: 2,
    estimatedTime: '5-10 min',
    featured: false,
  },

  // Action Games
  {
    id: 'snake',
    name: 'Snake Evolution',
    category: 'Action',
    description: 'Classic snake with power-ups and obstacles',
    icon: '🐍',
    color: '#22c55e',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '5-15 min',
    featured: true,
  },
  {
    id: 'pacman',
    name: 'Pac-Man Deluxe',
    category: 'Action',
    description: 'Eat dots, avoid ghosts, get power pellets',
    icon: '👻',
    color: '#facc15',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '10-20 min',
    featured: true,
  },
  {
    id: 'spaceinvaders',
    name: 'Space Invaders',
    category: 'Action',
    description: 'Defend Earth from alien invasion',
    icon: '👾',
    color: '#a855f7',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '5-15 min',
    featured: false,
  },
  {
    id: 'flappybird',
    name: 'Flappy Bird',
    category: 'Action',
    description: 'Tap to flap and avoid pipes',
    icon: '🐦',
    color: '#06b6d4',
    difficulty: 'hard',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '2-10 min',
    featured: false,
  },

  // Runner Games
  {
    id: 'templerun',
    name: 'Temple Run',
    category: 'Runner',
    description: 'Endless running through ancient temple',
    icon: '🏃',
    color: '#f59e0b',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '5-20 min',
    featured: true,
  },
  {
    id: 'subwaysurfers',
    name: 'Subway Surfers',
    category: 'Runner',
    description: 'Run on subway tracks and dodge trains',
    icon: '🚇',
    color: '#14b8a6',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '5-20 min',
    featured: true,
  },

  // Fighting
  {
    id: 'shadowfight',
    name: 'Shadow Fight',
    category: 'Fighting',
    description: 'Epic martial arts combat with combos',
    icon: '🥋',
    color: '#7c3aed',
    difficulty: 'hard',
    minPlayers: 1,
    maxPlayers: 2,
    estimatedTime: '5-15 min',
    featured: true,
  },

  // Sports Games
  {
    id: 'cricket',
    name: 'Hand Cricket',
    category: 'Sports',
    description: 'Classic hand cricket with batting & bowling',
    icon: '🏏',
    color: '#059669',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 2,
    estimatedTime: '10-20 min',
    featured: true,
  },
  {
    id: 'baseball',
    name: 'Baseball Pro',
    category: 'Sports',
    description: 'Hit home runs and strike out batters',
    icon: '⚾',
    color: '#dc2626',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 2,
    estimatedTime: '15-25 min',
    featured: false,
  },
  {
    id: 'football',
    name: 'Football Manager',
    category: 'Sports',
    description: 'Score goals and lead your team to victory',
    icon: '⚽',
    color: '#16a34a',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 2,
    estimatedTime: '15-30 min',
    featured: true,
  },
  {
    id: 'basketball',
    name: 'Basketball Stars',
    category: 'Sports',
    description: 'Shoot hoops and perform slam dunks',
    icon: '🏀',
    color: '#f97316',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 2,
    estimatedTime: '10-20 min',
    featured: false,
  },

  // Card & Board Games
  {
    id: 'poker',
    name: 'Texas Hold\'em Poker',
    category: 'Card',
    description: 'Classic poker with tournaments',
    icon: '🃏',
    color: '#b91c1c',
    difficulty: 'medium',
    minPlayers: 2,
    maxPlayers: 8,
    estimatedTime: '20-40 min',
    featured: true,
  },
  {
    id: 'blackjack',
    name: 'Blackjack 21',
    category: 'Card',
    description: 'Beat the dealer and get 21',
    icon: '🎴',
    color: '#dc2626',
    difficulty: 'easy',
    minPlayers: 1,
    maxPlayers: 5,
    estimatedTime: '5-15 min',
    featured: false,
  },
  {
    id: 'ludo',
    name: 'Ludo King',
    category: 'Board',
    description: 'Roll dice and race to home',
    icon: '🎲',
    color: '#eab308',
    difficulty: 'easy',
    minPlayers: 2,
    maxPlayers: 4,
    estimatedTime: '15-30 min',
    featured: true,
  },
  {
    id: 'monopoly',
    name: 'Property Tycoon',
    category: 'Board',
    description: 'Buy properties and bankrupt opponents',
    icon: '🏠',
    color: '#15803d',
    difficulty: 'medium',
    minPlayers: 2,
    maxPlayers: 6,
    estimatedTime: '45-90 min',
    featured: false,
  },

  // Arcade Games
  {
    id: 'breakout',
    name: 'Breakout Blitz',
    category: 'Arcade',
    description: 'Break all bricks with the ball',
    icon: '🧱',
    color: '#ea580c',
    difficulty: 'easy',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '5-15 min',
    featured: false,
  },
  {
    id: 'tetris',
    name: 'Tetris Classic',
    category: 'Arcade',
    description: 'Clear lines by arranging falling blocks',
    icon: '🔲',
    color: '#0891b2',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '10-30 min',
    featured: true,
  },
  {
    id: 'minesweeper',
    name: 'Minesweeper Expert',
    category: 'Arcade',
    description: 'Flag all mines without triggering them',
    icon: '💣',
    color: '#64748b',
    difficulty: 'hard',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '5-15 min',
    featured: false,
  },
  {
    id: 'towerdefense',
    name: 'Tower Defense',
    category: 'Arcade',
    description: 'Build towers to defend against waves',
    icon: '🗼',
    color: '#7c2d12',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedTime: '20-40 min',
    featured: true,
  },

  // Racing Games
  {
    id: 'carracing',
    name: 'Speed Racer',
    category: 'Racing',
    description: 'Race on multiple tracks with upgrades',
    icon: '🏎️',
    color: '#dc2626',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 4,
    estimatedTime: '5-15 min',
    featured: true,
  },
  {
    id: 'bikeracing',
    name: 'Moto Rush',
    category: 'Racing',
    description: 'High-speed motorcycle racing',
    icon: '🏍️',
    color: '#0284c7',
    difficulty: 'medium',
    minPlayers: 1,
    maxPlayers: 4,
    estimatedTime: '5-15 min',
    featured: false,
  },
];

export const CATEGORIES = [
  'All',
  'Puzzle',
  'Strategy',
  'Action',
  'Runner',
  'Fighting',
  'Sports',
  'Card',
  'Board',
  'Arcade',
  'Racing',
];
